### ISSUE TITLE
newer version

### ISSUE THREAD

**Issue by wwjzzz** [o2ac/o2ac-ur#10]
If I want to run it in a newer version of Ubuntu, do i need any changes? I failed.

**Comment by felixvd** [comment]
The docker container will run the same version of Ubuntu even if your host is running a newer version. No changes should be necessary as far as I am aware..

Which errors are you encountering during which operations?

**Comment by wwjzzz** [comment]
Thank you very much for your reply. I will try more. 
I'll ask you if there are any questions in the future.
