### ISSUE TITLE
Documentation Page Not Found

### ISSUE THREAD

**Issue by iamrajee** [o2ac/o2ac-ur#7]
The URL of [documentation](https://github.com/o2ac/o2ac-ur#:~:text=Read%20the-,documentation,-%2C%20check%20the%20Troubleshooting) in the `Quick Start` 5th point is broken.
![image](https://user-images.githubusercontent.com/25712145/151692451-cddd9e06-bf5a-442f-afb7-6efa9340c2f3.png)

**Comment by felixvd** [comment]
Thanks. I fixed it.
